[package]
name = "o4t"
description = "o4t, over-the-top-typing-test"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
ratatui = "0.29.0"
tokio = { version = "1.45.1", features = ["full"] }
